### PR TITLE
Make DocChip more reusable

### PR DESCRIPTION
**Pull request by gosteenBASIS**
I've made some simple changes to the DocChip file to make it easier to use. You can now set the "chip" parameter to either "shadow" or "name" to automatically populate the rest of the fields as needed for either a "renders with a shadow DOM" chip or a "name of component in the DOM" chip. For example:

Instead of this:
`<DocChip tooltipText="This component will render with a shadow DOM, an API built into the browser that facilitates encapsulation." label="Shadow" component="a" href="../../glossary#shadow-dom" target="_blank" clickable={true} iconName="shadow" />`

You can just do this:
`<DocChip chip='shadow' />`

Instead of this:
`<DocChip tooltipText="The name of the web component that will render in the DOM." label="dwc-field" clickable={false} iconName='code'/>`

Do this:
`<DocChip chip='name' label="dwc-field" />`

If we ever decide that all the shadow DOM chips should link somewhere (like the [Shadow DOM Glossary page](http://localhost:3000/docs/glossary#shadow-dom), it will be easy to change them all at once since that is all handled by the DocChip.js file. Likewise for changing any styling, icons, etc.

I changed some of the DocChips as an example, but it would be pretty easy to change most or all of them. 
These changes don't seem to break any of the existing DocChips, so we can migrate to the new format as slow or fast as we like.

### CODE REVIEW

**Comment by hyyan** [comment]
@gosteenBASIS good idea, please update the rest of the docs to use the new DocChip

**Comment by gosteenBASIS** [comment]
Updated the rest of the docs to the new, simpler DocChip format.

**Comment by hyyan** [comment]
@gosteenBASIS The client components are generated using the `create_files.js` script, not manually. Be sure to use the script to update the client components. Additionally, the description of the term "scoped" is technically incorrect and should be revised as shown in the following text below. Also, ensure the script checks whether the component is scoped or uses shadow DOM to use the correct chip.

`
This component is rendered without using the Shadow DOM, a browser API that enables encapsulation. Instead, it uses scoped components as an alternative approach. These components do not rely on the native Shadow DOM; instead, they scope their styles to avoid leaks or conflicts, offering a different method for style encapsulation.
`

**Comment by gosteenBASIS** [comment]
@hyyan Thanks for the info! I was wondering why the description for scoped and shadow components was the same. I've updated the create_files.js script to use the new format; the values for "encapsulation" in the JSON are the same as the DocChip names, so I think it's pretty straightforward. I also updated the DocChip file so the description of the Scoped chips matches the info you provided. I updated the wording a bit to make it a bit shorter and more direct:

`"This component uses scoped components, an alternative approach to the shadow DOM, a browser API that enables encapsulation. These components scope their styles to avoid leaks or conflicts instead of relying on the native shadow DOM."`

I ran the create_files.js program and it appears to be working correctly.

**Comment by hyyan** [comment]
@MatthewHawkins, could you please collaborate with @gosteenBASIS to ensure this is implemented correctly? The files should be generated in the `client-components` folder, and all file names must be in lowercase, for example, `alert-popover` instead of `Alert-popover`.

**Comment by MatthewHawkins** [comment]
Sure, I'll add that to the list to discuss on our Thursday meeting

**Comment by gosteenBASIS** [comment]
@MatthewHawkins @hyyan I believe this update is ready for final review.

**Review by MatthewHawkins — CHANGES_REQUESTED** [review]
Hey Garrison,

Looks good/cleaner implementation for the chips. 

The only change would be to please re-add the second <br> in the client articles, or give the chips a little bottom margin to avoid collision with the admonitions:

image

Otherwise I'd say we're set!

**Comment by hyyan** [comment]
@gosteenBASIS chips should be clickable and redirect the glossary page

**Review by hyyan — CHANGES_REQUESTED** [review]
@gosteenBASIS chips should be clickable and redirect the glossary page

**Comment by gosteenBASIS** [comment]
@hyyan @MatthewHawkins I made the shadow chip link to the Shadow DOM heading on the glossary page, and I added some margin-bottom styling on all the chips so they don't collide with the admonitions and we don't need the line breaks.

**Comment by MatthewHawkins** [comment]
Need a tweak to align these three components all together, and then we should be able to merge request:

image

**Comment by MatthewHawkins** [comment]
Pulled most recent changes, and this is the output that I get:
image

Should shoot for chips being aligned in a row.

**Comment by gosteenBASIS** [comment]
@bbrennanbasis I'm getting the following error with your latest changes:

`useRef is not defined
ReferenceError: useRef is not defined
    at JavadocLink (webpack-internal:///./src/components/DocsTools/JavadocLink.js:27:26)
    at renderWithHooks (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:16305:18)
    at mountIndeterminateComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20069:13)
...`

It looks like adding `useRef` to the import statement at the top will fix this:
`import React, { useState, useEffect, useRef } from 'react'`

However, your change doesn't work correctly when there is a JavadocLink but no DocChip:

image

I think we may need a separate component that houses the DocChips and JavadocLink, to ensure that a space is delegated to them regardless of which ones are there.

**Comment by gosteenBASIS** [comment]
Finally figured out a solution to the alignment issues without creating new components. The JavadocLink component now checks if there are DocChip components on the page, and wraps in a div if there aren't any, to ensure it gets aligned correctly in both cases:

image

image

**Comment by bbrennanbasis** [comment]
@hyyan This branch has been rebased and is ready for review.

**Comment by hyyan** [comment]
@bbrennanbasis this one has merge conflicts

**Comment by gosteenBASIS** [comment]
@hyyan I resolved the merge conflicts; I believe this is ready to go now. 
The Vale bot obviously has a lot of issues, but I don't think it's the responsibility of this particular pull request to address all of them, since the changes are just the result of merging, not actual changes from this issue.

**Review by MatthewHawkins — APPROVED** [review]

**Comment by MatthewHawkins** [comment]
@hyyan Went through and tested the articles, looks good to me - ready for your final review

**Comment by hyyan** [comment]
does not look good no small screens

overlap

**Comment by bbrennanbasis** [comment]
@hyyan Made a change for screens with a vw smaller than 500 pixels. 
 
mobile-view

**Comment by hyyan** [comment]
@MatthewHawkins, it looks good. Could you please resolve the conflict with the spinner and get it merged?

**Review by hyyan — APPROVED** [review]

**Pull request merged**
